/**
 * Seed data for Website Builder MVP
 *
 * Creates:
 * - One active template with placeholder HTML
 * - One test project with hostname 'test.sites.localhost'
 * - One draft page for the test project
 *
 * @see https://www.prisma.io/docs/guides/database/seed-database
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TEMPLATE_ID = 'template-professional-local-business';
const PROJECT_ID = 'project-test-site';
const PAGE_ID = 'page-test-homepage';

const placeholderHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{businessName}} - Welcome</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #333; }
    .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 4rem 2rem; text-align: center; }
    .hero h1 { font-size: 2.5rem; margin-bottom: 1rem; }
    .hero p { font-size: 1.25rem; opacity: 0.9; }
    .section { padding: 3rem 2rem; max-width: 800px; margin: 0 auto; }
    .section h2 { font-size: 1.75rem; margin-bottom: 1rem; color: #667eea; }
    .cta { background: #667eea; color: white; padding: 1rem 2rem; border: none; border-radius: 8px; font-size: 1rem; cursor: pointer; }
    .cta:hover { background: #5a67d8; }
    footer { background: #1a202c; color: #a0aec0; padding: 2rem; text-align: center; }
  </style>
</head>
<body>
  <header class="hero">
    <h1>{{businessName}}</h1>
    <p>{{tagline}}</p>
  </header>

  <main>
    <section class="section">
      <h2>About Us</h2>
      <p>{{description}}</p>
    </section>

    <section class="section">
      <h2>Our Services</h2>
      <p>{{services}}</p>
    </section>

    <section class="section" style="text-align: center;">
      <h2>Get in Touch</h2>
      <p>{{address}}</p>
      <p>{{phone}}</p>
      <br>
      <button class="cta">Contact Us</button>
    </section>
  </main>

  <footer>
    <p>&copy; 2024 {{businessName}}. All rights reserved.</p>
  </footer>
</body>
</html>`;

const testPageHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test Business - Welcome</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #333; }
    .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 4rem 2rem; text-align: center; }
    .hero h1 { font-size: 2.5rem; margin-bottom: 1rem; }
    .hero p { font-size: 1.25rem; opacity: 0.9; }
    .section { padding: 3rem 2rem; max-width: 800px; margin: 0 auto; }
    .section h2 { font-size: 1.75rem; margin-bottom: 1rem; color: #667eea; }
    footer { background: #1a202c; color: #a0aec0; padding: 2rem; text-align: center; }
  </style>
</head>
<body>
  <header class="hero">
    <h1>Test Business</h1>
    <p>Your trusted local partner</p>
  </header>

  <main>
    <section class="section">
      <h2>About Us</h2>
      <p>This is a test page generated by the Website Builder MVP seed script. If you can see this, hostname-based routing is working correctly!</p>
    </section>

    <section class="section">
      <h2>How It Works</h2>
      <p>This page is served from the database via hostname routing. The URL test.sites.localhost resolves to this project and renders this HTML.</p>
    </section>
  </main>

  <footer>
    <p>&copy; 2024 Test Business. All rights reserved.</p>
  </footer>
</body>
</html>`;

async function main() {
  console.log('Seeding database...');

  // Create template
  const template = await prisma.template.upsert({
    where: { id: TEMPLATE_ID },
    create: {
      id: TEMPLATE_ID,
      name: 'Professional Local Business',
      htmlTemplate: placeholderHtml,
      isActive: true,
    },
    update: {
      htmlTemplate: placeholderHtml,
      isActive: true,
    },
  });
  console.log(`Created template: ${template.name}`);

  // Create test project
  const project = await prisma.project.upsert({
    where: { id: PROJECT_ID },
    create: {
      id: PROJECT_ID,
      userId: 'test-user-1',
      generatedHostname: 'test.sites.localhost',
      status: 'CREATED',
    },
    update: {},
  });
  console.log(`Created project: ${project.generatedHostname}`);

  // Create draft page for the project
  const page = await prisma.page.upsert({
    where: { id: PAGE_ID },
    create: {
      id: PAGE_ID,
      projectId: PROJECT_ID,
      path: '/',
      version: 1,
      status: 'draft',
      htmlContent: testPageHtml,
    },
    update: {
      htmlContent: testPageHtml,
    },
  });
  console.log(`Created page: ${page.path} (version ${page.version}, status: ${page.status})`);

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
